server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /items {
        proxy_pass http://catalog-service:8080;
    }

    location /item {
        proxy_pass http://inventory-service:8080;
    }

    location /order {
        proxy_pass http://order-service:8080;
    }

    location /appt {
        proxy_pass http://appt-service:8080;
    }
}